export const cartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM:"REMOVE_ITEM",
  CLEAR_ITEM:"CLEAR_ITEM",
  CLEAR_CART:"CLEAR_CART",
  FETCH_CART_ITEM_START:"FETCH_CART_ITEM_START",
  FETCH_CART_ITEM_SUCCESS:"FETCH_CART_ITEM_SUCCESS",
  FETCH_CART_ITEM_FAILURE:"FETCH_CART_ITEM_FAILURE"
};
